#!/usr/bin/env python3
"""Create an immutable official snapshot and a typed derived data layer."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import stat
import sys
import time
import uuid

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq


OFFICIAL_FILES = [
    "comp_predict_table.csv",
    "mfd_bank_shibor.csv",
    "mfd_day_share_interest.csv",
    "user_balance_table.csv",
    "user_profile_table.csv",
]

SNAPSHOT_VERSION = "d002_official_csv_snapshot"
LAYER_VERSION = "d003_validated_data_layer_v2"
GENERATOR_VERSION = 1


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def read_official_hashes(raw_root: Path) -> dict[str, str]:
    hashes: dict[str, str] = {}
    manifest_path = raw_root / "manifest.sha256"
    for line in manifest_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        digest, name = line.split(maxsplit=1)
        hashes[name.lstrip(" *")] = digest
    if set(hashes) != set(OFFICIAL_FILES):
        raise ValueError("official hash manifest does not match the frozen file list")
    return hashes


def parquet_description(path: Path) -> dict[str, object]:
    parquet_file = pq.ParquetFile(path)
    schema = parquet_file.schema_arrow
    return {
        "path": path.name,
        "bytes": path.stat().st_size,
        "sha256": sha256(path),
        "rows": parquet_file.metadata.num_rows,
        "row_groups": parquet_file.metadata.num_row_groups,
        "schema": {field.name: str(field.type) for field in schema},
    }


def write_parquet(frame: pd.DataFrame, path: Path) -> dict[str, object]:
    table = pa.Table.from_pandas(frame, preserve_index=False)
    for column in ["report_date", "mfd_date"]:
        index = table.schema.get_field_index(column)
        if index >= 0:
            table = table.set_column(index, column, table[column].cast(pa.date32()))
    pq.write_table(
        table,
        path,
        compression="zstd",
        row_group_size=131_072,
        use_dictionary=True,
    )
    description = parquet_description(path)
    path.chmod(stat.S_IREAD | stat.S_IRGRP | stat.S_IROTH)
    return description


def build_snapshot(raw_root: Path, output_root: Path, expected: dict[str, str]) -> dict:
    copy_root = output_root / "csv"
    copy_root.mkdir(parents=True)
    files: list[dict[str, object]] = []
    for name in OFFICIAL_FILES:
        source = raw_root / name
        actual = sha256(source)
        if actual != expected[name]:
            raise ValueError(f"official source hash mismatch: {name}")
        target = copy_root / name
        shutil.copyfile(source, target)
        copied = sha256(target)
        if copied != actual:
            raise IOError(f"snapshot copy hash mismatch: {name}")
        files.append(
            {
                "path": f"csv/{name}",
                "bytes": target.stat().st_size,
                "sha256": copied,
                "source_path": f"data/raw/official/{name}",
                "byte_identical": True,
            }
        )
        target.chmod(stat.S_IREAD | stat.S_IRGRP | stat.S_IROTH)

    readme = """# Official CSV snapshot

This directory contains byte-for-byte copies of the five frozen official CSV files.
The copies are generated by `scripts/build_data_foundation.py`; hashes in
`manifest.json` must match `data/raw/official/manifest.sha256`.

Treat `csv/` as read-only. Create a new dataset version for every future change.
"""
    (output_root / "README.md").write_text(readme, encoding="utf-8")
    manifest = {
        "dataset_version": SNAPSHOT_VERSION,
        "generator_version": GENERATOR_VERSION,
        "generated_at": utc_now(),
        "generator": "scripts/build_data_foundation.py",
        "command": ".venv\\Scripts\\python.exe scripts\\build_data_foundation.py",
        "source_manifest": "data/raw/official/manifest.sha256",
        "files": files,
    }
    (output_root / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return manifest


def prepare_balance(raw_root: Path) -> pd.DataFrame:
    path = raw_root / "user_balance_table.csv"
    frame = pd.read_csv(path, dtype_backend="pyarrow")
    frame["report_date"] = pd.to_datetime(
        frame["report_date"].astype("string"), format="%Y%m%d"
    )

    for column in ["category1", "category2", "category3", "category4"]:
        frame[f"{column}_filled"] = frame[column].fillna(0).astype("int64[pyarrow]")

    expected_balance = (
        frame["yBalance"] + frame["total_purchase_amt"] - frame["total_redeem_amt"]
    )
    frame["balance_reconciliation_delta"] = (
        frame["tBalance"] - expected_balance
    ).astype("int64[pyarrow]")
    frame["balance_identity_ok"] = frame["balance_reconciliation_delta"].eq(0)
    frame["has_consume"] = frame["consume_amt"].gt(0)
    frame["has_consume_breakdown"] = frame[
        ["category1", "category2", "category3", "category4"]
    ].notna().all(axis=1)
    frame["purchase_log1p"] = np.log1p(frame["total_purchase_amt"].to_numpy()).astype(
        "float32"
    )
    frame["redeem_log1p"] = np.log1p(frame["total_redeem_amt"].to_numpy()).astype(
        "float32"
    )

    frame = frame.sort_values(["report_date", "user_id"], kind="stable").reset_index(
        drop=True
    )
    frame["user_id"] = frame["user_id"].astype("int32[pyarrow]")
    return frame


def prepare_profile(raw_root: Path) -> pd.DataFrame:
    frame = pd.read_csv(raw_root / "user_profile_table.csv", dtype_backend="pyarrow")
    frame["user_id"] = frame["user_id"].astype("int32[pyarrow]")
    frame["sex"] = frame["sex"].astype("int8[pyarrow]")
    frame["city"] = frame["city"].astype("category")
    frame["constellation"] = frame["constellation"].astype("category")
    return frame.sort_values("user_id", kind="stable").reset_index(drop=True)


def prepare_fund_yield(raw_root: Path) -> pd.DataFrame:
    frame = pd.read_csv(raw_root / "mfd_day_share_interest.csv", dtype_backend="pyarrow")
    frame["mfd_date"] = pd.to_datetime(
        frame["mfd_date"].astype("string"), format="%Y%m%d"
    )
    return frame.sort_values("mfd_date", kind="stable").reset_index(drop=True)


def prepare_shibor_daily(raw_root: Path, calendar: pd.DatetimeIndex) -> pd.DataFrame:
    observed = pd.read_csv(raw_root / "mfd_bank_shibor.csv", dtype_backend="pyarrow")
    observed["mfd_date"] = pd.to_datetime(
        observed["mfd_date"].astype("string"), format="%Y%m%d"
    )
    observed = observed.sort_values("mfd_date", kind="stable")
    rate_columns = [column for column in observed.columns if column != "mfd_date"]

    daily = pd.DataFrame({"mfd_date": calendar})
    daily = daily.merge(observed, on="mfd_date", how="left", validate="one_to_one")
    daily["is_shibor_observed"] = daily[rate_columns[0]].notna()
    last_observed = daily["mfd_date"].where(daily["is_shibor_observed"]).ffill()
    daily["days_since_observation"] = (daily["mfd_date"] - last_observed).dt.days.astype(
        "int16[pyarrow]"
    )
    daily[rate_columns] = daily[rate_columns].ffill()
    if daily[rate_columns].isna().any().any():
        raise ValueError("historical forward fill left missing SHIBOR values")
    return daily


def prepare_daily_aggregate(
    balance: pd.DataFrame,
    fund_yield: pd.DataFrame,
    shibor: pd.DataFrame,
) -> pd.DataFrame:
    first_dates = balance.groupby("user_id", observed=True)["report_date"].min()
    new_users = first_dates.value_counts().rename_axis("report_date").rename("new_users")
    grouped = balance.groupby("report_date", observed=True)
    daily = grouped.agg(
        rows=("user_id", "size"),
        users=("user_id", "nunique"),
        total_balance=("tBalance", "sum"),
        total_purchase_amt=("total_purchase_amt", "sum"),
        total_redeem_amt=("total_redeem_amt", "sum"),
        purchase_users=("total_purchase_amt", lambda values: int((values > 0).sum())),
        redeem_users=("total_redeem_amt", lambda values: int((values > 0).sum())),
        balance_identity_failures=("balance_identity_ok", lambda values: int((~values).sum())),
    ).reset_index()
    daily = daily.merge(new_users, on="report_date", how="left", validate="one_to_one")
    daily["new_users"] = daily["new_users"].fillna(0).astype("int32[pyarrow]")
    daily["purchase_log1p"] = np.log1p(daily["total_purchase_amt"].to_numpy())
    daily["redeem_log1p"] = np.log1p(daily["total_redeem_amt"].to_numpy())
    daily = daily.merge(
        fund_yield.rename(columns={"mfd_date": "report_date"}),
        on="report_date",
        how="left",
        validate="one_to_one",
    )
    daily = daily.merge(
        shibor.rename(columns={"mfd_date": "report_date"}),
        on="report_date",
        how="left",
        validate="one_to_one",
    )
    return daily.sort_values("report_date", kind="stable").reset_index(drop=True)


def build_layer(raw_root: Path, output_root: Path, source_hashes: dict[str, str]) -> dict:
    started = time.perf_counter()
    balance = prepare_balance(raw_root)
    profile = prepare_profile(raw_root)
    fund_yield = prepare_fund_yield(raw_root)
    calendar = pd.date_range(balance["report_date"].min(), balance["report_date"].max())
    shibor = prepare_shibor_daily(raw_root, calendar)
    daily = prepare_daily_aggregate(balance, fund_yield, shibor)

    outputs = [
        write_parquet(balance, output_root / "user_balance_daily.parquet"),
        write_parquet(profile, output_root / "user_profile.parquet"),
        write_parquet(fund_yield, output_root / "fund_yield_daily.parquet"),
        write_parquet(shibor, output_root / "shibor_daily.parquet"),
        write_parquet(daily, output_root / "daily_aggregate.parquet"),
    ]

    readme = """# Validated derived data layer

Typed, date-sorted Parquet tables derived only from frozen official data through
2014-08-31. Raw values are preserved. Structural category nulls remain nullable;
explicit `_filled` columns provide zero-filled values for computation.

`shibor_daily.parquet` uses historical forward fill only and includes observation
flags. `balance_reconciliation_delta` exposes source inconsistencies without
silently changing official balances.

Treat this directory as read-only. Rebuild with `scripts/build_data_foundation.py`
into a new dataset version when transformation logic changes.
"""
    (output_root / "README.md").write_text(readme, encoding="utf-8")
    manifest = {
        "dataset_version": LAYER_VERSION,
        "generator_version": GENERATOR_VERSION,
        "generated_at": utc_now(),
        "generator": "scripts/build_data_foundation.py",
        "command": ".venv\\Scripts\\python.exe scripts\\build_data_foundation.py",
        "competition_data_cutoff": "2014-08-31",
        "sort_contract": {
            "user_balance_daily.parquet": ["report_date", "user_id"],
            "user_profile.parquet": ["user_id"],
            "fund_yield_daily.parquet": ["mfd_date"],
            "shibor_daily.parquet": ["mfd_date"],
            "daily_aggregate.parquet": ["report_date"],
        },
        "transformations": {
            "category_nulls": "preserved; companion *_filled columns use zero",
            "shibor_calendar": "daily historical forward fill only",
            "balance_reconciliation": "delta exposed; official values unchanged",
            "extreme_values": "preserved; thresholds belong to fold-local modeling or audit only",
        },
        "sources": [
            {
                "path": f"data/raw/official/{name}",
                "sha256": source_hashes[name],
            }
            for name in OFFICIAL_FILES
        ],
        "files": outputs,
        "generator_sha256": sha256(Path(__file__).resolve()),
        "runtime": {
            "python": sys.version.split()[0],
            "pandas": pd.__version__,
            "pyarrow": pa.__version__,
        },
        "git": git_state(output_root.parents[2]),
        "elapsed_seconds": round(time.perf_counter() - started, 3),
    }
    (output_root / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return manifest


def git_state(project_root: Path) -> dict[str, object]:
    def run(*args: str) -> str:
        result = subprocess.run(
            ["git", *args],
            cwd=project_root,
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()

    try:
        status = run("status", "--porcelain")
        return {"commit": run("rev-parse", "HEAD"), "dirty": bool(status)}
    except (OSError, subprocess.CalledProcessError):
        return {"commit": None, "dirty": None}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    project_root = args.project_root.resolve()
    raw_root = project_root / "data" / "raw" / "official"
    derived_root = project_root / "data" / "derived"
    snapshot_final = derived_root / SNAPSHOT_VERSION
    layer_final = derived_root / LAYER_VERSION
    if layer_final.exists():
        print(f"Refusing to overwrite existing dataset version: {layer_final}", file=sys.stderr)
        return 2

    source_hashes = read_official_hashes(raw_root)
    token = uuid.uuid4().hex[:8]
    snapshot_temp = derived_root / f".{SNAPSHOT_VERSION}.building-{token}"
    layer_temp = derived_root / f".{LAYER_VERSION}.building-{token}"
    try:
        layer_temp.mkdir(parents=True)
        if snapshot_final.exists():
            snapshot_manifest = json.loads(
                (snapshot_final / "manifest.json").read_text(encoding="utf-8")
            )
            copied_hashes = {
                Path(row["path"]).name: row["sha256"]
                for row in snapshot_manifest["files"]
            }
            if copied_hashes != source_hashes:
                raise ValueError("existing official snapshot does not match frozen sources")
        else:
            snapshot_temp.mkdir(parents=True)
            build_snapshot(raw_root, snapshot_temp, source_hashes)
        build_layer(raw_root, layer_temp, source_hashes)
        if snapshot_temp.exists():
            snapshot_temp.rename(snapshot_final)
        layer_temp.rename(layer_final)
    finally:
        for path in [snapshot_temp, layer_temp]:
            if path.exists():
                shutil.rmtree(path)

    print(f"Verified {snapshot_final}")
    print(f"Created {layer_final}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
